# Generated by Django 3.0.3 on 2020-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('palce', models.CharField(max_length=40)),
                ('number', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.BigIntegerField()),
            ],
        ),
    ]
