# Generated by Django 3.0.3 on 2020-05-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ajax'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ajax',
            new_name='Ajreg',
        ),
    ]
